### ISSUE TITLE
Method "private void insertAtFront(E data) " in "DoublyLinkedList.java"

### ISSUE THREAD

**Issue by alphaveneno** [JWLee89/The-Coding-Delight#1]
"Line 155 this.tail = new Node<>(data);" results in the second insertion into an empty list (AKA the next insertion into a list with only one element) happening at the back, not the front.

Replace with:              	this.tail = this.head;
            	                        this.head = new Node<>(data);

**Comment by JWLee89** [comment]
@alphaveneno 

Thanks for pointing this out. On a quick glance through the code, I see that I am appending to the back in the case that there is only a single node (AKA the Head).

That was embarrassing haha. Thanks for pointing this out!

Quick update on changes. 

```
if (this.tail == null) {
    // this.tail = new Node<>(data); // Remove this. Sorry for this error. 

    // Apply your suggestion
    // since we are inserting in the front
    this.tail = this.head;  // current head becomes new tail
    this.head = new Node<>(data);
    // Lastly, update references
    // Head --> Tail
    // Head <-- Tail
    this.head.setNext(this.tail);
    this.tail.setPrev(this.head);
}
```

P.S. Sorry for the late response.

**Comment by alphaveneno** [comment]
No problem. I tested the original files and the amended files with a JUnit file designed by my prof for testing LinkedList. 
    On Tuesday, May 8, 2018, 7:49:05 p.m. CDT, Jay Lee <notifications@github.com> wrote:  
 
 
Thanks for pointing this out. When I have time, I will go through the code again and come back with an update.

**Comment by JWLee89** [comment]
@alphaveneno 

Hopefully the issues are resolved now. I am currently extremely strapped for time, which is why I haven't been able to blog. 

In the future, I was thinking about writing a blog post on Splay Trees when I have some time to spare. Just out of curiosity, are there any particular data structures or algorithms that you would like to see a blog post on? 

And thanks for your patience!
