### ISSUE TITLE
Method "public void removeAt(int index)" in "DoublyLinkedList.java"

### ISSUE THREAD

**Issue by alphaveneno** [JWLee89/The-Coding-Delight#2]
"Line 82:  this.size--;" is redundant and should be deleted. 

It results in double-decrementation of list size because "public void removeAt(int index)" calls "private void removeNode(Node<T> nodeToRemove)" which also decrements list size.

**Comment by JWLee89** [comment]
@alphaveneno You are right. That was embarrassing haha. Thank you for pointing that out. Updated the codebase accordingly. Thanks for pointing out the bugs! 

P.s. Really sorry about the delayed response. Really busy these days, so I haven't been able to blog or do much. 

Appreciate the thought and also pointing out these issues. Thanks once again!
